config/routes.rb
Rails.application.routes.draw do
  resources :featured_images
  root to: "posts#index"
  resources :posts
  resources :users
  resources :posts
  resources :users
  get  "background_process" => "background_process#index"
  post "background_process" => "background_process#background_process"

  get "posts_stats" => "stats#posts"
  get "posts_demo_csv" => "imports#posts_demo_csv"
  post "import_posts" => "imports#posts"
  post "like_post/:id" => "posts#like", as: :like_post
end

app/models/featured_image.rb
class FeaturedImage < ActiveRecord::Base
  belongs_to :post, touch: true
end

app/controllers/featured_images_controller.rb
class FeaturedImagesController < ApplicationController
  before_action :set_featured_image, only: [:show, :edit, :update, :destroy]

  # GET /featured_images
  # GET /featured_images.json
  def index
    @featured_images = FeaturedImage.all
  end

  # GET /featured_images/1
  # GET /featured_images/1.json
  def show
  end

  # GET /featured_images/new
  def new
    @featured_image = FeaturedImage.new
  end

  # GET /featured_images/1/edit
  def edit
  end

  # POST /featured_images
  # POST /featured_images.json
  def create
    @featured_image = FeaturedImage.new(featured_image_params)

    respond_to do |format|
      if @featured_image.save
        format.html { redirect_to @featured_image, notice: 'Featured image was successfully created.' }
        format.json { render :show, status: :created, location: @featured_image }
      else
        format.html { render :new }
        format.json { render json: @featured_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /featured_images/1
  # PATCH/PUT /featured_images/1.json
  def update
    respond_to do |format|
      if @featured_image.update(featured_image_params)
        format.html { redirect_to @featured_image, notice: 'Featured image was successfully updated.' }
        format.json { render :show, status: :ok, location: @featured_image }
      else
        format.html { render :edit }
        format.json { render json: @featured_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /featured_images/1
  # DELETE /featured_images/1.json
  def destroy
    @featured_image.destroy
    respond_to do |format|
      format.html { redirect_to featured_images_url, notice: 'Featured image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_featured_image
      @featured_image = FeaturedImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def featured_image_params
      params.require(:featured_image).permit(:url, :post_id)
    end
end

app/views/featured_images/_form.html.haml
= simple_form_for(@featured_image) do |f|
  = f.error_notification

  .form-inputs
    = f.input :url
    = f.association :post

  .form-actions
    = f.button :submit

app/views/featured_images/edit.html.haml
%h1 Editing featured_image

= render 'form'

= link_to 'Show', @featured_image
\|
= link_to 'Back', featured_images_path

app/views/featured_images/index.html.haml
%h1 Listing featured_images

%table
  %thead
    %tr
      %th Url
      %th Post
      %th
      %th
      %th

  %tbody
    - @featured_images.each do |featured_image|
      %tr
        %td= featured_image.url
        %td= featured_image.post.title
        %td= link_to 'Show', featured_image
        %td= link_to 'Edit', edit_featured_image_path(featured_image)
        %td= link_to 'Destroy', featured_image, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Featured image', new_featured_image_path

app/views/featured_images/new.html.haml
%h1 New featured_image

= render 'form'

= link_to 'Back', featured_images_path

app/views/featured_images/show.html.haml
%p#notice= notice

%p
  %b Url:
  = @featured_image.url
%p
  %b Post:
  = @featured_image.post

= link_to 'Edit', edit_featured_image_path(@featured_image)
\|
= link_to 'Back', featured_images_path