config/routes.rb
Rails.application.routes.draw do
  resources :featured_images
  root to: "posts#index"
  resources :posts
  resources :users
  resources :posts
  resources :users
  get  "background_process" => "background_process#index"
  post "background_process" => "background_process#background_process"

  get "posts_stats" => "stats#posts"
  get "posts_demo_csv" => "imports#posts_demo_csv"
  post "import_posts" => "imports#posts"
  post "like_post/:id" => "posts#like", as: :like_post
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  email      :string
#  first_name :string
#  last_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  role       :string
#

class User < ActiveRecord::Base
  has_many :posts
  after_save do
    posts.each {|post| post.touch}
  end

  def admin?
    role == "admin"
  end

  def editor?
    role == "editor"
  end

  def normal
    role.nil?
  end

  def to_s
    email
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email
    = f.input :first_name
    = f.input :last_name

  .form-actions
    = f.button :submit

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table.table
  %tr
    %th Email
    %th First name
    %th Last name
    %th Posts
  - @users.includes(:posts).each do |user|
    %tr
      %td= user.email
      %td= user.first_name
      %td= user.last_name
      %td
        %ul
          - user.posts.each do |post|
            %li= link_to post.title, post_path(post)
      %td
        = link_to 'Show', user, class: "btn btn-primary"
        = link_to 'Edit', edit_user_path(user), class: "btn btn-primary"
        = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

= link_to 'New User', new_user_path, class: "btn btn-primary"

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @user.email
%p
  %b First name:
  = @user.first_name
%p
  %b Last name:
  = @user.last_name

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path