config/routes.rb
Rails.application.routes.draw do
  resources :featured_images
  root to: "posts#index"
  resources :posts
  resources :users
  resources :posts
  resources :users
  get  "background_process" => "background_process#index"
  post "background_process" => "background_process#background_process"

  get "posts_stats" => "stats#posts"
  get "posts_demo_csv" => "imports#posts_demo_csv"
  post "import_posts" => "imports#posts"
  post "like_post/:id" => "posts#like", as: :like_post
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id             :integer          not null, primary key
#  title          :string
#  content        :text
#  user_id        :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  workflow_state :string
#  likes          :integer
#

class Post < ActiveRecord::Base
  belongs_to :user, touch: true
  has_one :featured_image
  include Workflow

  workflow do
    state :draft do
      event :done, :transitions_to => :for_review
    end
    state :for_review do
      event :accept, :transitions_to => :ready
      event :reject, :transitions_to => :draft
    end
    state :ready do
      event :publish, :transitions_to => :published
    end
    state :published
  end

  def accept
    puts "Post '#{id}' is ready to be published and needs approval"
  end

  def inspect
    "<Post title: #{title} state: #{workflow_state.inspect}>"
  end

  def likes
    sleep(0.1)
    #puts "TAKING SOME TIME!"
    read_attribute(:likes)
  end

  def like
    update_attributes(likes: likes + 1)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    allow!(authorizator.can?(:create_post)) do
      @post = Post.new
    end
  end

  def create
    allow!(authorizator.can?(:create_post)) do
      @post = Post.new(post_params)

      if @post.save
        Resque.enqueue(Notify, @post.id)
        redirect_to @post, notice: 'Post was successfully created.'
      else
        render :new
      end
    end
  end

  def destroy
    allow!(authorizator.can?(:create_post)) do
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end
  end

  def edit
    allow!(authorizator.can?(:modify_post))
  end

  def update
    allow!(authorizator.can?(:modify_post)) do
      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.'
      else
        render :edit
      end
    end
  end

  def like
    @post.like
    redirect_to :back, notice: "Liked!"
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end

  def most_popular_posts
    @most_popular_posts ||= Post.order("likes DESC").take(10)
  end
  helper_method :most_popular_posts
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= simple_form_for(@post) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :content
    = f.association :user

  .form-actions
    = f.button :submit

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
.row
  .col-sm-6
    %h1 Listing posts

    %table.table
      %tr
        %th Author
        %th Title
        %th Content
        %th Actions
      - @posts.includes(:user).each do |post|
        %tr
          %td= post.user
          %td= post.title
          %td #{post.content[0..30]} ...
          %td
            = link_to 'Show', post_path(post), class: "btn btn-primary"
            = link_to 'like', like_post_path(post), class: "btn btn-primary", method: :post
            - if authorizator.can?(:modify_post, post: post)
              = link_to 'Edit', edit_post_path(post), class: "btn btn-primary"
            - if authorizator.can?(:create_post)
              = link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"          
    - if authorizator.can?(:create_post)
      = link_to 'New Post', new_post_path, class: "btn btn-primary"

    = link_to 'Download Posts csv', posts_stats_path, class: "btn btn-primary"
    = link_to 'Download Posts csv demo for import', posts_demo_csv_path, class: "btn btn-primary"

    %br
    = form_tag import_posts_path, method: :post, multipart: true do
      %label(for="file") File to Upload
      = file_field_tag :csv
      = submit_tag "Import CSV", class: "btn btn-primary"
  .col-sm-6
    - cache most_popular_posts do
      .well.sidebar-nav
        %h3 Most popular posts
        %ul.nav.nav-list.navbar-inner
          - most_popular_posts.each do |post|
            %li
              %span
                = image_tag post.featured_image.url, size: "30x30"
                = link_to post.title, post
                %small (#{post.likes})
                %br
                %small by #{post.user}

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
- Mystique.present(@post, context: self) do |post|
  %h1= post.title
  %h2
    %small by
    %span= post.user

  .well
    = post.content

  Published on #{post.created_at}